_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: b79c91db-866b-4fa4-9723-aba3fc82a649
name: 'Innoraft Employee Management Portal'
mail: abhishek.kumar@innoraft.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/172
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: abhishek.kumar@innoraft.com
